#!/bin/bash

set -eux

run_node_with_cdt_cmd="docker run --rm -v "$PWD":/daobet.contracts -w /daobet.contracts -ti daocasino/daobet-with-cdt:latest"

cmd="${1:?}"
shift

case "$cmd" in
(build) eval "$run_node_with_cdt_cmd" ./cicd/build.sh ;;
(test)  eval "$run_node_with_cdt_cmd" ./build/tests/unit_test "$@" ;;
(pack)  eval "$run_node_with_cdt_cmd" ./cicd/pack.sh ;;
(login) eval "$run_node_with_cdt_cmd" bash ;;
(*)     echo >&2 "Invalid command: $cmd." ; exit 1 ;;
esac
